name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff flake8 bandit pip-audit pytest-cov

      # --- Dummy config copy for CI ---
      - name: Set up dummy config for CI
        run: |
          cp data/configs/conf_variables.example.py data/configs/conf_variables.py
          cp data/configs/question_mappings.example.py data/configs/question_mappings.py

      - name: Run Ruff linter
        run: |
          ruff check scripts/ tests/ utils/ --fix

      - name: Run Flake8 linter
        run: |
          flake8 scripts/ tests/ utils/

      - name: Run Bandit security scan
        run: |
          bandit -r scripts/ utils/

      - name: Run security audit (pip-audit)
        run: |
          pip-audit -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=scripts --cov=utils --cov-report=xml -v

      - name: Upload logs as artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/

      - name: Upload coverage report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
